export const productCategories = [
  'Bags',
  'Leather',
  'Gift',
  'Toy',
  'Household Appliances',
  'Electronics',
  'Mobile Accessories'
];

export const makeupStorageBags = [
  {
    id: 1,
    name: 'Makeup Storage Bag 1',
    image: '/static/images/bndbroad/productsImages/msb1.jpg',
    image1: '/static/images/bndbroad/productsImages/msb1_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb1_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb1_d_1.jpg',
    category: 'Bags',

    Item: '101237',
    applicableScenarios:
      'cosmetic storage, cosmetic bags, storage bags, bathroom storage, washing bags',
    supportDistribution: 'distribution is not supported',
    productCategory: 'cosmetic bag',
    bagSize: 'medium',
    bagInternalStructure: 'mobile phone bag',
    style: 'Korean version',
    material: 'PVC',
    pattern: 'solid color',
    popularElements: 'laser magic color',
    typeOfOuterBag: 'inner patch bag'
  },
  {
    id: 2,
    name: 'Makeup Storage Bag 2',
    image: '/static/images/bndbroad/productsImages/msb2.jpg',
    image1: '/static/images/bndbroad/productsImages/msb2_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb2_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb2_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    type: 'Bag',
    productName: 'Beauty Cosmetic Case',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 3,
    name: 'Makeup Storage Bag 3',
    image: '/static/images/bndbroad/productsImages/msb3.jpg',
    image1: '/static/images/bndbroad/productsImages/msb3_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb3_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb3_d_1.jpg',
    category: 'Bags',

    material: 'PVC',
    type: 'Bag',
    productName: 'Beauty Cosmetic Case',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 4,
    name: 'Makeup Storage Bag 4',
    image: '/static/images/bndbroad/productsImages/msb4.jpg',
    image1: '/static/images/bndbroad/productsImages/msb4_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb4_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb4_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    type: 'Bag',
    productName: 'Beauty Cosmetic Case',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 5,
    name: 'Makeup Storage Bag 5',
    image: '/static/images/bndbroad/productsImages/msb5.jpg',
    image1: '/static/images/bndbroad/productsImages/msb5_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb5_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb5_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    type: 'Bag',
    productName: 'Beauty Cosmetic Case',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 6,
    name: 'Makeup Storage Bag 6',
    image: '/static/images/bndbroad/productsImages/msb6.jpg',
    image1: '/static/images/bndbroad/productsImages/msb6_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb6_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb6_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    type: 'Bag',
    productName: 'Travel Large Cosmetic Bag',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 7,
    name: 'Makeup Storage Bag 7',
    image: '/static/images/bndbroad/productsImages/msb7.jpg',
    image1: '/static/images/bndbroad/productsImages/msb7_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb7_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb7_d_1.jpg',
    category: 'Bags',

    material: 'PVC',
    type: 'Bag',
    productName: 'Makeup Organizer Bags for Women',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 8,
    name: 'Makeup Storage Bag 8',
    image: '/static/images/bndbroad/productsImages/msb8.jpg',
    image1: '/static/images/bndbroad/productsImages/msb8_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb8_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb8_d_1.jpg',
    category: 'Bags',

    material: 'PVC',
    Type: 'Bag',
    ProductName: 'Beauty Cosmetic Case',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 9,
    name: 'Makeup Storage Bag 9',
    image: '/static/images/bndbroad/productsImages/msb9.jpg',
    image1: '/static/images/bndbroad/productsImages/msb9_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb9_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb9_d_1.jpg',
    category: 'Bags',

    material: 'PVC',
    type: 'Bag',
    productName: 'Beauty Cosmetic Case',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 10,
    name: 'Makeup Storage Bag 10',
    image: '/static/images/bndbroad/productsImages/msb10.jpg',
    image1: '/static/images/bndbroad/productsImages/msb10_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb10_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb10_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    type: 'Bag',
    productName: 'Make up bag travel for Women & Men',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion',
    color: 'Customized Color',
    logo: 'Accept Customized Logo',
    feature: 'Eco-friendly'
  },
  {
    id: 11,
    name: 'Makeup Storage Bag 11',
    image: '/static/images/bndbroad/productsImages/msb11.jpg',
    image1: '/static/images/bndbroad/productsImages/msb11_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb11_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb11_d_1.jpg',
    category: 'Bags',

    material: 'Pu',
    type: 'Bag',
    productName: 'Travel Toiletry Bag For Man and Women',
    use: 'This Makeup Bag not only can storage your cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion',
    color: 'Customized Color',
    logo: 'Accept Customized Logo',
    feature: 'Eco-friendly'
  },
  {
    id: 12,
    name: 'Makeup Storage Bag 12',
    image: '/static/images/bndbroad/productsImages/msb12.jpg',
    image1: '/static/images/bndbroad/productsImages/msb12_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb12_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb12_d_1.jpg',
    category: 'Bags',

    material: 'Pu',
    type: 'Bag',
    productName: 'Beauty Cosmetic Case',
    use: 'This Makeup Bag not only can storage your cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 13,
    name: 'Makeup Storage Bag 13',
    image: '/static/images/bndbroad/productsImages/msb13.jpg',
    image1: '/static/images/bndbroad/productsImages/msb13_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb13_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb13_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    Type: 'Bag',
    productName: 'Travel Makeup Train Case Makeup Case Makeup Bag',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion'
  },
  {
    id: 14,
    name: 'Makeup Storage Bag 14',
    image: '/static/images/bndbroad/productsImages/msb14.jpg',
    image1: '/static/images/bndbroad/productsImages/msb14_1.jpg',
    image2: '/static/images/bndbroad/productsImages/msb14_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/msb14_d_1.jpg',

    material: 'Polyester',
    type: 'Bag',
    productName: 'Beauty Cosmetic Case',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion',

    category: 'Bags'
  }
];

export const vehicleMountedBag = [
  {
    id: 201,
    name: 'Vehicle-mounted Bag',
    image: '/static/images/bndbroad/productsImages/vmb1.jpg',
    image1: '/static/images/bndbroad/productsImages/vmb1_1.jpg',
    image2: '/static/images/bndbroad/productsImages/vmb1_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/vmb1_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    Type: 'Trunk Organizer',
    placeOfOrigin: 'GuangDong China',
    brandName: 'OEM/ODM',
    modelNumber: 'EF-69',
    productName: 'organizer storage box in the trunk of a car',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fashion',
    style: 'Casual',
    feature: 'Comfortable'
  },
  {
    id: 202,
    name: 'Vehicle-mounted Bag 2',
    image: '/static/images/bndbroad/productsImages/vmb2.jpg',
    image1: '/static/images/bndbroad/productsImages/vmb2_1.jpg',
    image2: '/static/images/bndbroad/productsImages/vmb2_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/vmb2_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    Type: 'Back Seat Organizer',
    placeOfOrigin: 'GuangDong China',
    brandName: 'OEM',
    modelNumber: 'REW-85',
    productName: 'car organizer backseat',
    packing: '1pc/poly Bag',
    size: '9"x 5"x 2.5", Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    design: 'Fashion',
    style: 'Casual',
    feature: 'Comfortable'
  },
  {
    id: 203,
    name: 'Vehicle-mounted Bag 3',
    image: '/static/images/bndbroad/productsImages/vmb3.jpg',
    image1: '/static/images/bndbroad/productsImages/vmb3_1.jpg',
    image2: '/static/images/bndbroad/productsImages/vmb3_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/vmb3_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    Type: 'Trunk Organizer',
    placeOfOrigin: 'GuangDong China',
    brandName: 'OEM/ODM',
    modelNumber: 'FRE-6987',
    productName: 'organizer storage box in the trunk of a car',
    packing: '1pc/poly Bag',
    size: '9"x 5"x 2.5", Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    design: 'Fashion',
    style: 'Casual',
    feature: 'Comfortable'
  },
  {
    id: 204,
    name: 'Vehicle-mounted Bag 4',
    image: '/static/images/bndbroad/productsImages/vmb4.jpg',
    image1: '/static/images/bndbroad/productsImages/vmb4_1.jpg',
    image2: '/static/images/bndbroad/productsImages/vmb4_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/vmb4_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    Type: 'Trunk Organizer',
    placeOfOrigin: 'JiangXi China',
    brandName: 'ENMINGZEYU',
    modelNumber: 'E20-332215',
    productName: 'car garbage trash can storage bag',
    packing: '1pc/poly Bag',
    size: '9"x 5"x 2.5", Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    design: 'Fashion',
    style: 'Casual',
    feature: 'Comfortable',
    carFitment: 'JEEP, Jeep - Europe',
    model: 'Wrangler JK, Wrangler III, Wrangler IV, Wrangler II, Wrangler',
    year: '2011-2016, 2010-2016, 2007-2016, 1996-2007, 2002-2007, 2006-2008, 2017-2019, 2016-2018, 2018-2018, 1993-1997'
  },
  {
    id: 205,
    name: 'Vehicle-mounted Bag 5',
    image: '/static/images/bndbroad/productsImages/vmb5.jpg',
    image1: '/static/images/bndbroad/productsImages/vmb5_1.jpg',
    image2: '/static/images/bndbroad/productsImages/vmb5_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/vmb5_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    Type: 'Trunk Organizer',
    placeOfOrigin: 'JiangXi China',
    brandName: 'ENMINGZEYU',
    modelNumber: 'E20-1125',
    productName: 'Roll bar Storage Bag Organizer',
    packing: '1pc/poly Bag',
    size: '9"x 5"x 2.5", Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Acceptable',
    function: 'Suitable for all groups',
    design: 'Fashion',
    style: 'Casual',
    feature: 'Comfortable',
    carFitment: 'JEEP, Jeep - Europe',
    model: 'Wrangler JK, Wrangler III, Wrangler IV, Wrangler II, Wrangler',
    year: '2011-2016, 2010-2016, 2007-2016, 1996-2007, 2002-2007, 2006-2008, 2017-2019, 2016-2018, 2018-2018, 1993-1997'
  }
];

export const shoppingBag = [
  {
    id: 301,
    name: 'Shopping Bag',
    image: '/static/images/bndbroad/productsImages/sb1.jpg',
    image1: '/static/images/bndbroad/productsImages/sb1_1.jpg',
    image2: '/static/images/bndbroad/productsImages/sb1_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/sb1_d_1.jpg',
    category: 'Bags',

    product: 'shopping bags',
    import: 'or not: no',
    brand: 'adh5520',
    specifications: '45 * 38.5 * cm',
    type: 'medium',
    origin: 'China',
    applicableGender: 'general',
    maximumLoad: '150g',
    material: 'umbrella cloth',
    style: 'Europe and America / portable'
  },
  {
    id: 302,
    name: 'Shopping Bag',
    image: '/static/images/bndbroad/productsImages/sb2.jpg',
    image1: '/static/images/bndbroad/productsImages/sb2_1.jpg',
    image2: '/static/images/bndbroad/productsImages/sb2_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/sb2_d_1.jpg',
    category: 'Bags',

    product: 'shopping bags',
    import: 'or not: no',
    brand: 'adh5520',
    specifications: '45 * 38.5 * cm',
    type: 'medium',
    origin: 'China',
    applicableGender: 'general',
    maximumLoad: '150g',
    material: 'Polyester',
    style: 'Folding, Newest Fashinable'
  }
];

export const mommyBag = [
  {
    id: 401,
    name: 'Mommy Bag',
    image: '/static/images/bndbroad/productsImages/mb1.jpg',
    image1: '/static/images/bndbroad/productsImages/mb1_1.jpg',
    image2: '/static/images/bndbroad/productsImages/mb1_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/mb1_d_1.jpg',
    category: 'Bags',

    material: 'Oxford',
    placeOfOrigin: 'JiangXi China',
    brandName: 'Jastle',
    modelNumber: 'JTMM001-6',
    size: '36*24*16cm',
    color: 'Black,Blue,Green,Red,Pink,Blue+Red,Watermelon Red, or customized',
    weight: '0.45kg',
    mOQ: '15Pcs',
    logo: 'Customer Logo',
    packing: '1pc/poly Bag + Carton',
    productName: 'Diaper backpack bag',
    usage: 'Baby Products Organizer Bag',
    function: 'Multi-function Mommy Bag',
    service: 'Accept OEM ODM'
  },
  {
    id: 402,
    name: 'Mommy Bag 2',
    image: '/static/images/bndbroad/productsImages/mb2.jpg',
    image1: '/static/images/bndbroad/productsImages/mb2_1.jpg',
    image2: '/static/images/bndbroad/productsImages/mb2_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/mb2_d_1.jpg',
    category: 'Bags',

    Item: '1012555',
    ProductCategory: 'diaper towel',
    ImportOrNot: 'no',
    Brand: 'CXL',
    ApplicablePeople: 'general',
    Material: 'nylon',
    PackingQuantity: '50',
    Dimensions: '66*55cm',
    Packing: 'opp bag',
    Specifications: 'medium size',
    WhetherCrossBorderExportIsExclusivelyForSupply: 'yes'
  },
  {
    id: 403,
    name: 'Mommy Bag 3',
    image: '/static/images/bndbroad/productsImages/mb3.jpg',
    image1: '/static/images/bndbroad/productsImages/mb3_1.jpg',
    image2: '/static/images/bndbroad/productsImages/mb3_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/mb3_d_1.jpg',
    category: 'Bags',

    Item: '10221',
    ProductCategory: 'baby carriage bag',
    ImportOrNot: 'no',
    Brand: 'CXL',
    origin: 'JiangXi China',
    colors: 'black, green, blue and gray',
    Material: 'nylon',
    Packing: 'opp bag',
    Specifications: '31*20*16cm',
    WhetherCrossBorderExportIsExclusivelyForSupply: 'yes'
  }
];

export const fireProofBag = [
  {
    id: 501,
    name: 'Fireproof Bag',
    image: '/static/images/bndbroad/productsImages/fpb1.jpg',
    image1: '/static/images/bndbroad/productsImages/fpb1_1.jpg',
    image2: '/static/images/bndbroad/productsImages/fpb1_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/fpb1_d_1.jpg',
    category: 'Bags',

    brand: 'cxl',
    item: 'A097',
    type: '1240',
    material: 'fireproof material',
    addLogo: 'yes',
    machiningCustomization: 'yes',
    style: 'zipper type',
    copeOfApplication: 'portfolio',
    materialThickness: '0.5 (mm)',
    commodityWeight: '3500g',
    size: 'can be customized (mm)',
    specifications: 'can be customized'
  }
];

export const femaleBag = [
  {
    id: 601,
    name: 'Female Bag',
    image: '/static/images/bndbroad/productsImages/fb1.jpg',
    image1: '/static/images/bndbroad/productsImages/fb1_1.jpg',
    image2: '/static/images/bndbroad/productsImages/fb1_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/fpb1_d_1.jpg',
    category: 'Bags',

    style: 'Korean version / women"s handbag',
    goodsSourceCategory: 'ordering',
    item: '10120010',
    supportDistribution: 'distribution is not supported',
    materialQuality: 'PU',
    textureOfLining: 'nylon',
    bagShape: 'horizontal square',
    bagTrendStyle: 'locomotive bag',
    openingMethod: 'zipper buckle',
    popularElements: 'simplicity',
    bagInternalStructure: 'mobile phone bag, sandwich zipper bag'
  },
  {
    id: 602,
    name: 'Female Bag 2',
    image: '/static/images/bndbroad/productsImages/fb2.jpg',
    image1: '/static/images/bndbroad/productsImages/fb2_1.jpg',
    image2: '/static/images/bndbroad/productsImages/fb2_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/fpb2_d_1.jpg',
    category: 'Bags',

    style: 'Korean version / women"s handbag',
    goodsSourceCategory: 'ordering',
    item: 'a096',
    supportDistribution: 'distribution is not supported',
    materialQuality: 'PU',
    textureOfLining: 'nylon',
    bagShape: 'horizontal square',
    bagTrendStyle: 'small square bag',
    openingMethod: 'zipper',
    popularElements: 'elements:plush',
    bagInternalStructure: 'ID bag, mobile phone bag and mezzanine zipper bag'
  },
  {
    id: 603,
    name: 'Female Bag 3',
    image: '/static/images/bndbroad/productsImages/fb3.jpg',
    image1: '/static/images/bndbroad/productsImages/fb3_1.jpg',
    image2: '/static/images/bndbroad/productsImages/fb3_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/fpb3_d_1.jpg',
    category: 'Bags',

    style: 'Korean version / women"s shoulder bag',
    goodsSourceCategory: 'ordering',
    item: '10195',
    supportDistribution: 'distribution is not supported',
    materialQuality: 'PU',
    textureOfLining: 'dacron',
    bagShape: 'Vertical square shape',
    bagTrendStyle: 'Jelly bag',
    openingMethod: 'open',
    popularElements: 'transparent'
  }
];

export const sportOutDoorBag = [
  {
    id: 701,
    name: 'Sports, Outdoor Bag',
    image: '/static/images/bndbroad/productsImages/sodb1.jpg',
    image1: '/static/images/bndbroad/productsImages/sodb1_1.jpg',
    image2: '/static/images/bndbroad/productsImages/sodb1_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/sodb1_d_1.jpg',
    category: 'Bags',

    productCategory: 'travel bag/travel bag',
    goodsSourceCategory: 'ordering',
    Item: 'A089',
    supportDistribution: 'distribution is not supported',
    bagSize: 'large',
    capacity: '56-75l',
    bagInternalStructure:
      'zip pocket, mobile phone pocket, certificate pocket, sandwich zipper pocket, computer insertion pocket',
    openingMethod: 'zipper',
    withOrWithoutTieRod: 'no',
    withLockOrNot: 'no',
    material: 'Oxford cloth',
    numberOfShoulderStraps: 'single'
  },
  {
    id: 702,
    name: 'Sports, Outdoor Bag 2',
    image: '/static/images/bndbroad/productsImages/sodb2.jpg',
    image1: '/static/images/bndbroad/productsImages/sodb2_1.jpg',
    image2: '/static/images/bndbroad/productsImages/sodb2_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/sodb2_d_1.jpg',
    category: 'Bags',

    origin: 'Shenzhen',
    importOrNot: 'no',
    specifications: 'customizable',
    addLogo: 'yes',
    style: 'bundle pocket, backpack bag',
    color: 'customizable',
    use: 'storage bag',
    machiningCustomization: 'yes',
    printingTechnology: 'machine embroidery, screen printing, offset printing, machine printing',
    brand: 'CXL',
    item: '101303'
  },
  {
    id: 703,
    name: 'Sports, Outdoor Bag 3',
    image: '/static/images/bndbroad/productsImages/sodb3.jpg',
    image1: '/static/images/bndbroad/productsImages/sodb3_1.jpg',
    image2: '/static/images/bndbroad/productsImages/sodb3_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/sodb3_d_1.jpg',
    category: 'Bags',

    productCategory: 'travel bag/travel bag',
    goodsSourceCategory: 'ordering',
    item: '10363',
    supportDistribution: 'distribution is not supported',
    bagSize: 'large',
    capacity: '36-55L',
    bagInternalStructure: 'zip pocket, mobile phone pocket, certificate pocket, sandwich zipper pocket, computer pocket and camera pocket',
    openingMethod: 'zipper',
    withOrWithoutTieRod: 'no',
    withLockOrNot: 'no',
    material: 'canvas',
    numberOfShoulderStraps: 'two',
    liftingParts: 'soft handle',
    feature:
      'waterproof, storage, wear-resistant, anti-theft, earthquake-resistant and load-reducing',
    typeOfAccessories: 'none'
  }
];

export const cosmeticBag = [
  {
    id: 801,
    name: 'Cosmetic Bag',
    image: '/static/images/bndbroad/productsImages/cb1.jpg',
    image1: '/static/images/bndbroad/productsImages/cb1_1.jpg',
    image2: '/static/images/bndbroad/productsImages/cb1_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/cb1_d_1.jpg',
    category: 'Bags',

    brand: 'CXL',
    importOrNot: 'no',
    material: 'nylon',
    style: 'Korean',
    tradeAttribute: 'domestic trade',
    origin: 'JiangXi China',
    productCategory: 'ordering',
    function: 'storage and finishing',
    scopeOfApplication: 'washing and storage',
    patent: 'no',
    applicableScene: 'wash'
  },
  {
    id: 802,
    name: 'Cosmetic Bag 2',
    image: '/static/images/bndbroad/productsImages/cb2.jpg',
    image1: '/static/images/bndbroad/productsImages/cb2_1.jpg',
    image2: '/static/images/bndbroad/productsImages/cb2_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/cb2_d_1.jpg',
    category: 'Bags',

    brand: 'CXL',
    importOrNot: 'no',
    material: 'Oxford cloth',
    style: 'Korean',
    tradeAttribute: 'domestic trade',
    origin: 'JiangXi China',
    productCategory: 'ordering',
    function: 'storage bag',
    scopeOfApplication: ' travel storage',
    patent: 'no',
    applicableScene: 'wash',
    colors: 'green, blue and black'
  },
  {
    id: 803,
    name: 'Cosmetic Bag 3',
    image: '/static/images/bndbroad/productsImages/cb3.jpg',
    image1: '/static/images/bndbroad/productsImages/cb3_1.jpg',
    image2: '/static/images/bndbroad/productsImages/cb3_2.jpg',
    imaged1: '/static/images/bndbroad/productsImages/cb3_d_1.jpg',
    category: 'Bags',

    material: 'Polyester',
    type: 'Bag',
    productName: 'cosmetic bag',
    use: 'perfect place for all your toiletries and cosmetics',
    packing: '1pc/poly Bag',
    size: 'Custom Size Accepted',
    moq: '500Pcs',
    oemOdm: 'Accepable',
    function: 'Suitable for all groups',
    usage: 'Suitable for Many Occasions',
    design: 'Fasihon'
  }
];

export const indexBagProducts = [
  cosmeticBag[0],
  vehicleMountedBag[0],
  sportOutDoorBag[0],
  makeupStorageBags[0],
  femaleBag[0],
  mommyBag[0],
  shoppingBag[0],
  fireProofBag[0]
];

export const allBags = makeupStorageBags.concat(
  vehicleMountedBag,
  shoppingBag,
  mommyBag,
  fireProofBag,
  cosmeticBag
);
